Resources:
  LPDemoUser:
    Type: AWS::IAM::User
    Properties:
      UserName: LPDemoUser
      Policies:
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'

  LPDemoUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref LPDemoUser

  LPDemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.prefixStageService}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  LPDemoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LPDemoBucket
      PolicyDocument:
        Statement:
          Action: 's3:GetObject'
          Effect: Allow
          Principal: '*'
          Resource: !Sub "${LPDemoBucket.Arn}/*"

  LPDemoAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: ${env:WORDPRESS_IMAGE}
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            RuntimeEnvironmentVariables:
              - Name: WORDPRESS_DB_HOST 
                Value: !GetAtt LPDemoDatabase.Endpoint.Address
              - Name: WORDPRESS_DB_NAME 
                Value: ${env:DB_NAME}
              - Name: WORDPRESS_DB_USER
                Value: ${env:DB_USERNAME}
              - Name: WORDPRESS_DB_PASSWORD
                Value: ${env:DB_PASSWORD}
              - Name: WORDPRESS_TABLE_PREFIX
                Value: wp_
              - Name: WORDPRESS_DEBUG
                Value: false
            Port: 80
      InstanceConfiguration:
        Cpu: 1024
        Memory: 2048
      ServiceName: ${self:custom.prefixStageService}
      HealthCheckConfiguration:
        Protocol: TCP
        Path: "/"
        Interval: 10
        Timeout: 5
        HealthyThreshold: 2
        UnhealthyThreshold: 2

  LPDemoDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: ${self:custom.prefixStageService}-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: ${env:DB_USERNAME}
      MasterUserPassword: ${env:DB_PASSWORD}
      DBName: ${env:DB_NAME}
      PubliclyAccessible: true

Outputs:
  LPDemoAppRunnerServiceUrl:
    Description: "URL of the App Runner Service"
    Value: !GetAtt LPDemoAppRunnerService.ServiceUrl
  LPDemoRDSInstanceEndpoint:
    Description: "RDS MySQL instance endpoint"
    Value: !GetAtt LPDemoDatabase.Endpoint.Address
  LPDemoRDSInstancePort:
    Description: "RDS MySQL instance port"
    Value: !GetAtt LPDemoDatabase.Endpoint.Port
  LPDemoRDSInstancePass:
    Description: "RDS MySQL instance pass"
    Value: ${env:DB_PASSWORD}
  LPDemoRDSInstanceUser:
    Description: "RDS MySQL instance user"
    Value: ${env:DB_USERNAME}
  LPDemoUserAccessKey:
    Description: "LPDemoUser AccessKey"
    Value: !Ref LPDemoUserAccessKey
  LPDemoUserSecretKey:
    Description: "LPDemoUser SecretKey"
    Value: !GetAtt LPDemoUserAccessKey.SecretAccessKey