name: LP Wordpress 3blocks deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Set stage
      id: set-stage
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          echo "stage=prod" >> $GITHUB_ENV
        else
          echo "stage=${{ github.ref_name }}" >> $GITHUB_ENV
        fi
    - name: Set up environment
      run: |
        touch .env
        
        echo "WORDPRESS_IMAGE=${{ vars.WORDPRESS_IMAGE }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

        cat .env
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage ${{ env.stage }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
